# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/abby/UnrealEngine

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	SampleThirdPerson-Android-DebugGame  \
	SampleThirdPerson-Android-Development  \
	SampleThirdPerson-Android-Shipping  \
	SampleThirdPerson-Linux-DebugGame  \
	SampleThirdPerson-Linux-Development  \
	SampleThirdPerson-Linux-Shipping  \
	SampleThirdPerson-LinuxArm64-DebugGame  \
	SampleThirdPerson-LinuxArm64-Development  \
	SampleThirdPerson-LinuxArm64-Shipping  \
	SampleThirdPerson \
	SampleThirdPersonEditor-Linux-DebugGame  \
	SampleThirdPersonEditor-Linux-Development  \
	SampleThirdPersonEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend SampleThirdPersonEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug SampleThirdPersonEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

SampleThirdPerson-Android-DebugGame:
	 $(BUILD) SampleThirdPerson Android DebugGame  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-Android-Development:
	 $(BUILD) SampleThirdPerson Android Development  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-Android-Shipping:
	 $(BUILD) SampleThirdPerson Android Shipping  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-Linux-DebugGame:
	 $(BUILD) SampleThirdPerson Linux DebugGame  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-Linux-Development:
	 $(BUILD) SampleThirdPerson Linux Development  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-Linux-Shipping:
	 $(BUILD) SampleThirdPerson Linux Shipping  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-LinuxArm64-DebugGame:
	 $(BUILD) SampleThirdPerson LinuxArm64 DebugGame  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-LinuxArm64-Development:
	 $(BUILD) SampleThirdPerson LinuxArm64 Development  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson-LinuxArm64-Shipping:
	 $(BUILD) SampleThirdPerson LinuxArm64 Shipping  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPerson: SampleThirdPerson-Linux-Development

SampleThirdPersonEditor-Linux-DebugGame:
	 $(BUILD) SampleThirdPersonEditor Linux DebugGame  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPersonEditor-Linux-Development:
	 $(BUILD) SampleThirdPersonEditor Linux Development  -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" $(ARGS)

SampleThirdPersonEditor: SampleThirdPersonEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/abby/workspace/unreal-engine/SampleThirdPerson/SampleThirdPerson.uproject" -Game 

.PHONY: $(TARGETS)
